FROM node:22-alpine AS builder
WORKDIR /web

COPY web/package.json web/package-lock.json* ./
RUN npm install

COPY web ./
RUN npm run build

FROM nginx:alpine AS runtime
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /web/dist /usr/share/nginx/html

EXPOSE 80
